kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
- kind: ServiceAccount
  name: traefik-ingress-controller
  namespace: staging

---

kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: staging
  annotations:
    external-dns.alpha.kubernetes.io/hostname: staging.antinvestor.com