apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: info@antinvestor.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    http01: {}

---

apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: letsencrypt
spec:
  secretName: letsencrypt-prod
  dnsNames:
  - 'antinvestor.com'
  - 'www.antinvestor.com'
  - 'api.antinvestor.com'
  acme:
    config:
    - http01:
        ingressClass: traefik
      domains:
      - 'antinvestor.com'
      - 'www.antinvestor.com'
      - 'api.antinvestor.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  