version: '3'
services:
  
    notification_db:
      image: postgres:latest
      environment:
        POSTGRES_DB: service_notification
        POSTGRES_USER: ant
        POSTGRES_PASSWORD: secret

    migrate:
      build: .

      depends_on:
        - notification_db
      environment:
        - LOG_LEVEL=debug
        - DO_MIGRATION=true
        - DATABASE_URL=postgres://ant:secret@notification_db:5432/service_notification?sslmode=disable
      restart: on-failure


    