version: '3'
services:
  
    db:
      image: postgres:alpine
      container_name: db
      hostname: db
      environment:
        POSTGRES_DB: service_notification
        POSTGRES_USER: ant
        POSTGRES_PASSWORD: ant-secret
      ports:
        - "5432:5432"
                  

    app:
      build: .
      command: ["go", "run", "main.go"]
      hostname: app
    
      ports:
        - "7000:7000"
      depends_on: 
        - db
      links: 
        - db       

    nats:
        image: nats-streaming:latest
        restart: always
        # depends_on:
        #   - db
        command: -m 8222 --store file --dir ./data --max_msgs 0 --max_bytes 0
        ports:
          - "4222"
          - "8222:8222"


    