apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: service-notification
  namespace: dataplane 
spec:
  teamId: "ones"
  volume:
    size: 10Gi
    storageClass: ssd-storage
  numberOfInstances: 2
  users:
    filesmanx:
      - superuser
    filesman: 
      - login
    filesmans: 
      - login
  databases:
    servicefiles: filesman
    servicefilesstag: filesmans
  postgresql:
    version: "11"
    parameters:
      shared_buffers: "64MB"
      max_connections: "20"
      log_statement: "all"
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 500Mi
  # restore a Postgres DB with point-in-time-recovery 
  # with a non-empty timestamp, clone from an S3 bucket using the latest backup before the timestamp
  # with an empty/absent timestamp, clone from an existing alive cluster using pg_basebackup
  # clone:
  #  uid: "efd12e58-5786-11e8-b5a7-06148230260c"
  #  cluster: "acid-batman"
  #  timestamp: "2017-12-19T12:40:33+01:00" # timezone required (offset relative to UTC, see RFC 3339 section 5.6)
  # maintenanceWindows:
  #   - 01:00-06:00 #UTC
