// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification/notification.proto

package notification

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//QueueRequest for Queue Request with these defined requirements
type QueueRequest struct {
	ProfileID            map[string]string `protobuf:"bytes,1,rep,name=profileID,proto3" json:"profileID,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Massagetemplete      string            `protobuf:"bytes,2,opt,name=massagetemplete,proto3" json:"massagetemplete,omitempty"`
	Language             string            `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Massagevariables     map[string]string `protobuf:"bytes,4,rep,name=massagevariables,proto3" json:"massagevariables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Channel              string            `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	Autosend             string            `protobuf:"bytes,6,opt,name=autosend,proto3" json:"autosend,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueueRequest) Reset()         { *m = QueueRequest{} }
func (m *QueueRequest) String() string { return proto.CompactTextString(m) }
func (*QueueRequest) ProtoMessage()    {}
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{0}
}

func (m *QueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueRequest.Unmarshal(m, b)
}
func (m *QueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueRequest.Marshal(b, m, deterministic)
}
func (m *QueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueRequest.Merge(m, src)
}
func (m *QueueRequest) XXX_Size() int {
	return xxx_messageInfo_QueueRequest.Size(m)
}
func (m *QueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueueRequest proto.InternalMessageInfo

func (m *QueueRequest) GetProfileID() map[string]string {
	if m != nil {
		return m.ProfileID
	}
	return nil
}

func (m *QueueRequest) GetMassagetemplete() string {
	if m != nil {
		return m.Massagetemplete
	}
	return ""
}

func (m *QueueRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *QueueRequest) GetMassagevariables() map[string]string {
	if m != nil {
		return m.Massagevariables
	}
	return nil
}

func (m *QueueRequest) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *QueueRequest) GetAutosend() string {
	if m != nil {
		return m.Autosend
	}
	return ""
}

type QueueResponse struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	Messagestatus        string   `protobuf:"bytes,2,opt,name=messagestatus,proto3" json:"messagestatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{1}
}

func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (m *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(m, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *QueueResponse) GetMessagestatus() string {
	if m != nil {
		return m.Messagestatus
	}
	return ""
}

type StatusRequest struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{2}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

type StatusResponse struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	Messagestatus        string   `protobuf:"bytes,2,opt,name=messagestatus,proto3" json:"messagestatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{3}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *StatusResponse) GetMessagestatus() string {
	if m != nil {
		return m.Messagestatus
	}
	return ""
}

type ReleaseRequest struct {
	NotificationID       string   `protobuf:"bytes,1,opt,name=notificationID,proto3" json:"notificationID,omitempty"`
	Releasemassage       string   `protobuf:"bytes,2,opt,name=releasemassage,proto3" json:"releasemassage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReleaseRequest) Reset()         { *m = ReleaseRequest{} }
func (m *ReleaseRequest) String() string { return proto.CompactTextString(m) }
func (*ReleaseRequest) ProtoMessage()    {}
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{4}
}

func (m *ReleaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseRequest.Unmarshal(m, b)
}
func (m *ReleaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseRequest.Marshal(b, m, deterministic)
}
func (m *ReleaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseRequest.Merge(m, src)
}
func (m *ReleaseRequest) XXX_Size() int {
	return xxx_messageInfo_ReleaseRequest.Size(m)
}
func (m *ReleaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseRequest proto.InternalMessageInfo

func (m *ReleaseRequest) GetNotificationID() string {
	if m != nil {
		return m.NotificationID
	}
	return ""
}

func (m *ReleaseRequest) GetReleasemassage() string {
	if m != nil {
		return m.Releasemassage
	}
	return ""
}

type IncomeRequest struct {
	ProfileID            map[string]string `protobuf:"bytes,1,rep,name=profileID,proto3" json:"profileID,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Requeststatus        string            `protobuf:"bytes,2,opt,name=requeststatus,proto3" json:"requeststatus,omitempty"`
	Massagetype          string            `protobuf:"bytes,3,opt,name=massagetype,proto3" json:"massagetype,omitempty"`
	Language             string            `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Product              string            `protobuf:"bytes,5,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *IncomeRequest) Reset()         { *m = IncomeRequest{} }
func (m *IncomeRequest) String() string { return proto.CompactTextString(m) }
func (*IncomeRequest) ProtoMessage()    {}
func (*IncomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff76f27cb6af8e56, []int{5}
}

func (m *IncomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncomeRequest.Unmarshal(m, b)
}
func (m *IncomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncomeRequest.Marshal(b, m, deterministic)
}
func (m *IncomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncomeRequest.Merge(m, src)
}
func (m *IncomeRequest) XXX_Size() int {
	return xxx_messageInfo_IncomeRequest.Size(m)
}
func (m *IncomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncomeRequest proto.InternalMessageInfo

func (m *IncomeRequest) GetProfileID() map[string]string {
	if m != nil {
		return m.ProfileID
	}
	return nil
}

func (m *IncomeRequest) GetRequeststatus() string {
	if m != nil {
		return m.Requeststatus
	}
	return ""
}

func (m *IncomeRequest) GetMassagetype() string {
	if m != nil {
		return m.Massagetype
	}
	return ""
}

func (m *IncomeRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *IncomeRequest) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func init() {
	proto.RegisterType((*QueueRequest)(nil), "notification.QueueRequest")
	proto.RegisterMapType((map[string]string)(nil), "notification.QueueRequest.MassagevariablesEntry")
	proto.RegisterMapType((map[string]string)(nil), "notification.QueueRequest.ProfileIDEntry")
	proto.RegisterType((*QueueResponse)(nil), "notification.QueueResponse")
	proto.RegisterType((*StatusRequest)(nil), "notification.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "notification.StatusResponse")
	proto.RegisterType((*ReleaseRequest)(nil), "notification.ReleaseRequest")
	proto.RegisterType((*IncomeRequest)(nil), "notification.IncomeRequest")
	proto.RegisterMapType((map[string]string)(nil), "notification.IncomeRequest.ProfileIDEntry")
}

func init() { proto.RegisterFile("notification/notification.proto", fileDescriptor_ff76f27cb6af8e56) }

var fileDescriptor_ff76f27cb6af8e56 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x93, 0xad, 0x65, 0x67, 0x4b, 0x98, 0x0c, 0x48, 0x56, 0x40, 0xa2, 0x8a, 0x26, 0x54,
	0xb8, 0x28, 0x68, 0x5c, 0x80, 0x10, 0xda, 0x05, 0x63, 0x82, 0x5e, 0xf0, 0xd7, 0xdd, 0x21, 0x40,
	0x78, 0xd9, 0x59, 0x89, 0x48, 0xed, 0x10, 0xdb, 0x95, 0xfa, 0x20, 0x3c, 0x00, 0xef, 0xc0, 0x03,
	0xa2, 0x26, 0xf6, 0x88, 0xbd, 0x52, 0xa8, 0xd0, 0xee, 0x72, 0x8e, 0xbf, 0x73, 0xce, 0x77, 0xe2,
	0xef, 0x33, 0xdc, 0xe6, 0x42, 0xe5, 0x67, 0x79, 0xc6, 0x54, 0x2e, 0xf8, 0xfd, 0x76, 0x30, 0x2c,
	0x2b, 0xa1, 0x04, 0xd9, 0x69, 0xe7, 0xd2, 0x9f, 0x21, 0xec, 0xbc, 0xd3, 0xa8, 0x71, 0x8c, 0xdf,
	0x34, 0x4a, 0x45, 0x5e, 0xc0, 0x56, 0x59, 0x89, 0xb3, 0xbc, 0xc0, 0xd1, 0x73, 0xda, 0xe9, 0x87,
	0x83, 0xed, 0xfd, 0xbb, 0x43, 0xa7, 0x4d, 0x1b, 0x3e, 0x7c, 0x6b, 0xb1, 0x47, 0x5c, 0x55, 0xf3,
	0xf1, 0xef, 0x5a, 0x32, 0x80, 0xab, 0x53, 0x26, 0x25, 0x9b, 0xa0, 0xc2, 0x69, 0x59, 0xa0, 0x42,
	0x1a, 0xf4, 0x3b, 0x83, 0xad, 0xb1, 0x9f, 0x26, 0x09, 0x5c, 0x29, 0x18, 0x9f, 0x68, 0x36, 0x41,
	0x1a, 0xd6, 0x90, 0xf3, 0x98, 0x7c, 0x80, 0x5d, 0x03, 0x9f, 0xb1, 0x2a, 0x67, 0x27, 0x05, 0x4a,
	0xba, 0x51, 0xb3, 0x7a, 0xb0, 0x82, 0xd5, 0x2b, 0xaf, 0xa4, 0x21, 0x77, 0xa1, 0x13, 0xa1, 0xd0,
	0xcb, 0xbe, 0x30, 0xce, 0xb1, 0xa0, 0x9b, 0xf5, 0x60, 0x1b, 0x2e, 0x38, 0x31, 0xad, 0x84, 0x44,
	0x7e, 0x4a, 0xbb, 0x0d, 0x27, 0x1b, 0x27, 0x4f, 0x21, 0x76, 0xd7, 0x26, 0xbb, 0x10, 0x7e, 0xc5,
	0x39, 0xed, 0xd4, 0xc0, 0xc5, 0x27, 0xb9, 0x0e, 0x9b, 0x33, 0x56, 0x68, 0xbb, 0x73, 0x13, 0x3c,
	0x09, 0x1e, 0x77, 0x92, 0x43, 0xb8, 0xb1, 0x94, 0xde, 0x3a, 0x4d, 0xd2, 0x8f, 0x10, 0x99, 0x85,
	0x65, 0x29, 0xb8, 0x44, 0x72, 0x07, 0xe2, 0xf6, 0xef, 0xa8, 0xef, 0x6e, 0x51, 0xe3, 0x65, 0xc9,
	0x1e, 0x44, 0x53, 0xac, 0xa7, 0x4b, 0xc5, 0x94, 0x96, 0xa6, 0xb5, 0x9b, 0x4c, 0x1f, 0x41, 0x74,
	0x5c, 0x7f, 0x59, 0x55, 0xfc, 0x63, 0xfb, 0xf4, 0x13, 0xc4, 0xb6, 0xf0, 0x52, 0x88, 0x7d, 0x86,
	0x78, 0x8c, 0x05, 0x32, 0x89, 0x6b, 0x32, 0x5b, 0xe0, 0xaa, 0xa6, 0xd2, 0xa8, 0xc0, 0x0c, 0xf0,
	0xb2, 0xe9, 0xf7, 0x00, 0xa2, 0x11, 0xcf, 0xc4, 0xf4, 0x7c, 0xc2, 0xcb, 0x8b, 0x8e, 0xb8, 0xe7,
	0x6a, 0xcf, 0xc1, 0xaf, 0xb0, 0xc4, 0x1e, 0x44, 0x55, 0x03, 0x72, 0x77, 0x74, 0x92, 0xa4, 0x0f,
	0xdb, 0xd6, 0x21, 0xf3, 0xd2, 0x3a, 0xa2, 0x9d, 0x72, 0x0c, 0xb3, 0xe1, 0x19, 0x86, 0x42, 0xaf,
	0xac, 0xc4, 0xa9, 0xce, 0x94, 0x95, 0xb4, 0x09, 0xff, 0x4f, 0xb6, 0xfb, 0x3f, 0x02, 0xb8, 0xf6,
	0xba, 0xb5, 0xf4, 0x31, 0x56, 0xb3, 0x3c, 0x43, 0x72, 0x00, 0xe1, 0x1b, 0xad, 0x48, 0xf2, 0x67,
	0x37, 0x26, 0x37, 0x97, 0x9e, 0x19, 0x7d, 0x1c, 0x42, 0xb7, 0x51, 0x0c, 0xf1, 0x60, 0x8e, 0x00,
	0x93, 0x5b, 0xcb, 0x0f, 0x4d, 0x93, 0x23, 0xe8, 0x19, 0x59, 0x10, 0x0f, 0xe8, 0xaa, 0xe5, 0x2f,
	0x6d, 0x0e, 0x20, 0x18, 0x71, 0x9f, 0x87, 0x73, 0xb9, 0x2b, 0x77, 0x79, 0x16, 0xbf, 0x77, 0x1e,
	0xd7, 0x93, 0x6e, 0xfd, 0xe2, 0x3e, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x35, 0xee, 0x45, 0xe0,
	0x94, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationServiceClient interface {
	//Out method for queueing massages as requested
	Out(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error)
	//CommunicationStatus request to determine if notification is prepared or released
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	//QueueRelease method for releasing queued massages and returns if notification status if released
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	//In method is for client request for particular notification respones from system
	In(ctx context.Context, in *IncomeRequest, opts ...grpc.CallOption) (*QueueResponse, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) Out(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Out", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/Release", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) In(ctx context.Context, in *IncomeRequest, opts ...grpc.CallOption) (*QueueResponse, error) {
	out := new(QueueResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/In", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	//Out method for queueing massages as requested
	Out(context.Context, *QueueRequest) (*QueueResponse, error)
	//CommunicationStatus request to determine if notification is prepared or released
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	//QueueRelease method for releasing queued massages and returns if notification status if released
	Release(context.Context, *ReleaseRequest) (*StatusResponse, error)
	//In method is for client request for particular notification respones from system
	In(context.Context, *IncomeRequest) (*QueueResponse, error)
}

// UnimplementedNotificationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (*UnimplementedNotificationServiceServer) Out(ctx context.Context, req *QueueRequest) (*QueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Out not implemented")
}
func (*UnimplementedNotificationServiceServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedNotificationServiceServer) Release(ctx context.Context, req *ReleaseRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (*UnimplementedNotificationServiceServer) In(ctx context.Context, req *IncomeRequest) (*QueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method In not implemented")
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_Out_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Out(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Out",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Out(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/Release",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_In_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).In(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/In",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).In(ctx, req.(*IncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Out",
			Handler:    _NotificationService_Out_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _NotificationService_Status_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _NotificationService_Release_Handler,
		},
		{
			MethodName: "In",
			Handler:    _NotificationService_In_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification/notification.proto",
}
